export const TYPES = {
  LEER_BASE_DE_DATOS: "LEER_BASE_DE_DATOS",

  AGREGAR_AL_CARRITO: "AGREGAR_AL_CARRITO",
  ELIMINAR_UNO_DEL_CARRITO: "ELIMINAR_UNO_DEL_CARRITO",
  ELIMINAR_TODO_DEL_CARRITO: "ELIMINAR_TODO_DEL_CARRITO",
  LIMPIAR_EL_CARRITO: "LIMPIAR_EL_CARRITO",
};
